name: CI-run-cypress-tests-ci

on:
  push:
    branches: [ level-1-diy-rickard-kodar-utan-ai  ]
  pull_request:
    branches: [  level-1-diy-rickard-kodar-utan-ai ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: '20'
      - run: npm install
      - run: npm test